[package]
name = "artemis-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

## eth
alloy = { workspace = true, features = ["full", "node-bindings"] }
phyllo = { version = "0.3.0", features = ["rustls-tls-native-roots"] }

## async
async-trait = "0.1.64"
async-sse = "5.1.0"
reqwest = { version = "0.11.14", default-features = false, features = ["rustls-tls", "json", "stream"] }
tokio = { version = "1.18", features = ["full"] }
tokio-stream = { version = "0.1", features = ['sync'] }
futures-util = "0.3"

## misc
anyhow = "1.0.70"
chrono = { version = "0.4.19", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1.37"
url = { version = "2.2.2", features = ["serde"] }
