[package]
name = "opensea-sudo-arb"
version = "0.1.0"
edition = "2021"

[dependencies]

## eth
alloy = { workspace = true, features = ["providers", "rpc-types"] }
alloy-primitives.workspace = true
artemis-core = { path = "../../artemis-core" }
bindings = { path = "./bindings" }
opensea-v2 = { path = "../../clients/opensea-v2" }

## async
async-trait = "0.1.64"

## misc
anyhow = "1.0.70"
tracing = "0.1.37"

[dev-dependencies]
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
